version: '3.8'

services:
  odataasm-se172360-chapter04.api:
    image: ${DOCKER_REGISTRY-}odataasmse172360chapter04api
    build:
      context: .
      dockerfile: OdataAsm-SE172360-Chapter04.API/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=AppDb;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    ports:
      - "9090:8080"
      - "9091:8081"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
